### ISSUE TITLE
Code for evaluating the whole dataset

### ISSUE THREAD

**Issue by Morefre** [LituRout/PSLD#1]
Thanks for the great work ! I wonder is it possible for you to release the code for evaluating the algorithms on the whole dataset instead of a single image?

**Comment by LituRout** [comment]
Here you can find how we iterate over the dataset to evaluate on multiple images:
https://github.com/LituRout/PSLD/blob/508b0d3302cf89ade1d9688993d363a3684fafce/diffusion-posterior-sampling/sample_condition.py#L91C5-L91C5
