### ISSUE TITLE
Requirement for the set up for the Latent Diffusion model (LDM-VQ-4) 

### ISSUE THREAD

**Issue by csy2077** [LituRout/PSLD#7]
Hi, I appreciate the nice job.

We also want to try the process of posterior sampling with the Latent Diffusion model (LDM-VQ-4) mentioned in your paper, but it seems that there is no code using the Latent Diffusion model (LDM-VQ-4). 

Do you have a plan to release the code using the LDM-VQ-4?

**Comment by LituRout** [comment]
Hi csy2077,

Thanks for the comment. The code for posterior sampling using LDM-VQ-4 is already there in our codebase. Please take a look here: [https://github.com/LituRout/PSLD/blob/main/stable-diffusion/run/inverse_sr_ldm.sh](https://github.com/LituRout/PSLD/blob/main/stable-diffusion/run/inverse_sr_ldm.sh).

It is important to note that we have not carefully tuned the hyper-parameters for LDM-VQ-4 as our goal was to leverage SD-V1.5. The given hyper-parameters of LDM were suggested by another group of researchers. If these parameters do not work, you might want to tune the parameters depending on your application. 

Best,
Litu

**Comment by csy2077** [comment]
Hi Litu,

Thanks a lot for your reply and your answer is really helpful !

Best,
csy2077
